Trie trie = new ();
Console.WriteLine(trie.Add("balda"));
Console.WriteLine(trie.Add("babolda"));
Console.WriteLine(trie.Add("kniga"));
Console.WriteLine(trie.Contains("kniga"));
Console.WriteLine(trie.Contains("nekniga"));
Console.WriteLine(trie.Size);
Console.WriteLine(trie.HowManyStartsWithPrefix("b"));
Console.WriteLine(trie.HowManyStartsWithPrefix("u"));
Console.WriteLine(trie.HowManyStartsWithPrefix("k"));
Console.WriteLine(trie.Remove("nekniga"));
Console.WriteLine(trie.Remove("balda"));
Console.WriteLine(trie.Remove("kniga"));
Console.WriteLine(trie.HowManyStartsWithPrefix("b"));
Console.WriteLine(trie.Size);